name: test-preact-x

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - main

jobs:
  build_test:
    name: Build & Test Preact X
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test
        env:
          CI: false
