name: test-preact-x

on:
  pull_request:
    branches:
      - 'v1-preact-x'
  push:
    branches:
      - v1-preact-x

jobs:
  build_test:
    name: Build & Test Preact X
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          CI: false
          DEBUG: true
